### ISSUE TITLE
problem with running the bot

### ISSUE THREAD

**Issue by HeroJJ555** [shahriyardx/discord-music#1]
I have a problem with running a bot:
Console says:
PS C:\Users\Ryzen\Desktop\music> python main.py
Traceback (most recent call last):
    bot = MusicBot(command_prefix=PREFIX, intents=intents)
  File "C:\Users\Ryzen\Desktop\music\main.py", line 23, in __init__
    self.wavelink = wavelink.Client(bot=self)
AttributeError: module 'wavelink' has no attribute 'Client'

Could someone help me?

**Comment by shahriyardx** [comment]
I think you have installed the latest lavalink with this, Thats the problem

Install wavelink==0.9.10 and discord.py==1.7.3
